In [1]:
import pandas as pd

# reading and writing excel/csv file

In [2]:
df1=pd.read_csv('list.csv')
df1

   Unnamed: 0     Name  Marks  Age
0           0   swapna     98   21
1           1    tunia     89   21
2           2     paro     97   22
3           3  parbati     93   23
4           4     puja     95   24
5           5  narmada     94   23
6           6     rutu     93   22

In [3]:
df1.head()

   Unnamed: 0     Name  Marks  Age
0           0   swapna     98   21
1           1    tunia     89   21
2           2     paro     97   22
3           3  parbati     93   23
4           4     puja     95   24

In [4]:
df2=pd.read_excel('file_example.xls')
df2

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [5]:
df1.columns

Index(['Unnamed: 0', 'Name', 'Marks', 'Age'], dtype='str')

In [6]:
def convert_gender(cell):
    if cell =='Female':
        return 'Women'
    elif cell == 'Male':
        return 'Men'

def convert_country(cell):
    if cell =='United States':
        return 'USA'

df3=pd.read_excel('file_example.xls',sheet_name='Data',converters={'Gender':convert_gender,'Country':convert_country})  
df3

       Name Gender Country  Age    Id
0     Dulce  Women     USA   32  1562
1      Mara  Women     NaN   25  1582
2    Philip    Men     NaN   36  2587
3  Kathleen  Women     USA   25  3549
4   Nereida  Women     USA   58  2468
5    Gaston    Men     USA   24  2554
6      Etta  Women     NaN   56  3598
7   Earlean  Women     USA   27  2456
8  Vincenza  Women     USA   40  6548

In [7]:
df4=pd.read_excel('file_example.xls',header=4)
df4

   4  Kathleen   Hanner  Female  United States  25  15/10/2017  3549
0  5   Nereida  Magwood  Female  United States  58  16/08/2016  2468
1  6    Gaston    Brumm    Male  United States  24  21/05/2015  2554
2  7      Etta     Hurn  Female  Great Britain  56  15/10/2017  3598
3  8   Earlean   Melgar  Female  United States  27  16/08/2016  2456
4  9  Vincenza  Weiland  Female  United States  40  21/05/2015  6548

In [8]:
df1

   Unnamed: 0     Name  Marks  Age
0           0   swapna     98   21
1           1    tunia     89   21
2           2     paro     97   22
3           3  parbati     93   23
4           4     puja     95   24
5           5  narmada     94   23
6           6     rutu     93   22

In [10]:
df3

       Name Gender Country  Age    Id
0     Dulce  Women     USA   32  1562
1      Mara  Women     NaN   25  1582
2    Philip    Men     NaN   36  2587
3  Kathleen  Women     USA   25  3549
4   Nereida  Women     USA   58  2468
5    Gaston    Men     USA   24  2554
6      Etta  Women     NaN   56  3598
7   Earlean  Women     USA   27  2456
8  Vincenza  Women     USA   40  6548