# pandas

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
array1=np.array([[1,2,3,4],[5,6,7,8]])
a1=pd.DataFrame(array1)
a1

   0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [4]:
a2=pd.DataFrame([[1,2,34,5],[3,45,67,8]],columns=['A','B','C','D'])
a2

   A   B   C  D
0  1   2  34  5
1  3  45  67  8

In [5]:
a3=pd.DataFrame([1,2,3,4],columns=['A'])
a3

   A
0  1
1  2
2  3
3  4

In [6]:
a3=pd.DataFrame({
    "Name":['swapna','tunia','paro','parbati','puja','narmada','rutu'],
    'Marks':[98,89,97,93,95,94,93],
    'Age':[21,21,22,23,24,23,22]
})
a3

      Name  Marks  Age
0   swapna     98   21
1    tunia     89   21
2     paro     97   22
3  parbati     93   23
4     puja     95   24
5  narmada     94   23
6     rutu     93   22

In [7]:
a3.to_csv('list.csv')

In [8]:
a3.to_csv("false_indexing remove.csv",index = False)

In [9]:
a3.head(2)

     Name  Marks  Age
0  swapna     98   21
1   tunia     89   21

In [10]:
a3.tail(2)

      Name  Marks  Age
5  narmada     94   23
6     rutu     93   22

In [11]:
a3.describe()

           Marks        Age
count   7.000000   7.000000
mean   94.142857  22.285714
std     2.968084   1.112697
min    89.000000  21.000000
25%    93.000000  21.500000
50%    94.000000  22.000000
75%    96.000000  23.000000
max    98.000000  24.000000

In [30]:
a5=pd.read_excel('Book1.xlsx')
a5

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [14]:
a6=pd.read_csv('false_indexing remove.csv')
a6

      Name  Marks  Age
0   swapna     98   21
1    tunia     89   21
2     paro     97   22
3  parbati     93   23
4     puja     95   24
5  narmada     94   23
6     rutu     93   22

In [15]:
a6['Name']

0     swapna
1      tunia
2       paro
3    parbati
4       puja
5    narmada
6       rutu
Name: Name, dtype: str

In [16]:
a6['Name'][0]

'swapna'

In [ ]:
a6['Name'][1]='hii'

In [17]:
a6

      Name  Marks  Age
0   swapna     98   21
1    tunia     89   21
2     paro     97   22
3  parbati     93   23
4     puja     95   24
5  narmada     94   23
6     rutu     93   22

In [18]:
a6.index=['A','B','C','D','E','F','G']

In [19]:
a6

      Name  Marks  Age
A   swapna     98   21
B    tunia     89   21
C     paro     97   22
D  parbati     93   23
E     puja     95   24
F  narmada     94   23
G     rutu     93   22

In [20]:
a3=pd.DataFrame({
    "Name":['swapna','tunia','paro'],
    'age':[23,56,89]
})
a3

     Name  age
0  swapna   23
1   tunia   56
2    paro   89

In [23]:
a4=pd.DataFrame([[1,2],[4,7],[8,9]])
a4

   0  1
0  1  2
1  4  7
2  8  9

In [24]:
a4.describe()

              0         1
count  3.000000  3.000000
mean   4.333333  6.000000
std    3.511885  3.605551
min    1.000000  2.000000
25%    2.500000  4.500000
50%    4.000000  7.000000
75%    6.000000  8.000000
max    8.000000  9.000000

In [25]:
a4.corr()

          0         1
0  1.000000  0.947697
1  0.947697  1.000000

In [26]:
a4.count()

0    3
1    3
dtype: int64

In [27]:
a4.median()

0    4.0
1    7.0
dtype: float64